// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApiyX5TbvPNMonNnGbMC9qWALqdT3q76c',
    appId: '1:492719085289:web:5fe12032be2d6804294278',
    messagingSenderId: '492719085289',
    projectId: 'mob3ubg2024klp06-75444',
    authDomain: 'mob3ubg2024klp06-75444.firebaseapp.com',
    storageBucket: 'mob3ubg2024klp06-75444.firebasestorage.app',
    measurementId: 'G-X3Z8HQD8PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAdrX4IKvyEzHFY8KlTkx1g-ROy3ZRiQ',
    appId: '1:492719085289:android:00a1901ecfe476b8294278',
    messagingSenderId: '492719085289',
    projectId: 'mob3ubg2024klp06-75444',
    storageBucket: 'mob3ubg2024klp06-75444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD99xJSyS4kmcR1xCKjmxCE9NxQ4rptf0',
    appId: '1:492719085289:ios:3144aba95fd3fdb9294278',
    messagingSenderId: '492719085289',
    projectId: 'mob3ubg2024klp06-75444',
    storageBucket: 'mob3ubg2024klp06-75444.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApiyX5TbvPNMonNnGbMC9qWALqdT3q76c',
    appId: '1:492719085289:web:0604be048c9e016a294278',
    messagingSenderId: '492719085289',
    projectId: 'mob3ubg2024klp06-75444',
    authDomain: 'mob3ubg2024klp06-75444.firebaseapp.com',
    storageBucket: 'mob3ubg2024klp06-75444.firebasestorage.app',
    measurementId: 'G-BRG4EKP4YC',
  );
}
